### ISSUE TITLE
Remove export:unofficial

### ISSUE THREAD

**Issue by JoeCohen** [MushroomObserver/mushroom-observer#2023]
Remove `export:unofficial` from `rake lang` tasks (fixing any tests that break).
The task adds 5-10 seconds to deploys. 

@pellaea removed the task in #2010, but temporarily reinstated it in #2016 because it caused test failures in CI.

**Comment by JoeCohen** [comment]
The relevant failures are:
```ruby
ERROR TranslationsControllerTest#test_authorization_user_el (14.98s)
Minitest::UnexpectedError:         Errno::ENOENT: No such file or directory @ rb_sysopen - /home/runner/work/mushroom-observer/mushroom-observer/config/locales/el.txt
            app/controllers/translations_controller.rb:214:in `initialize'
            app/controllers/translations_controller.rb:214:in `open'
            app/controllers/translations_controller.rb:214:in `build_index'
            app/controllers/translations_controller.rb:[14](https://github.com/MushroomObserver/mushroom-observer/actions/runs/8242469524/job/22541465170#step:12:15):in `index'
            app/controllers/application_controller.rb:226:in `catch_errors_and_log_request_stats'
            test/functional_test_case.rb:23:in `get'
            test/controllers/translations_controller_test.rb:152:in `test_authorization_user_el'
...
ERROR LanguageTrackingIntegrationTest#test_language_tracking (197.82s)
Minitest::UnexpectedError:         Errno::ENOENT: No such file or directory @ rb_sysopen - /home/runner/work/mushroom-observer/mushroom-observer/config/locales/el.txt
            app/controllers/translations_controller.rb:214:in `initialize'
            app/controllers/translations_controller.rb:214:in `open'
            app/controllers/translations_controller.rb:214:in `build_index'
            app/controllers/translations_controller.rb:14:in `index'
            app/controllers/application_controller.rb:226:in `catch_errors_and_log_request_stats'
            test/integration/capybara/language_tracking_integration_test.rb:26:in `block in test_language_tracking'
            test/integration/capybara/language_tracking_integration_test.rb:[15](https://github.com/MushroomObserver/mushroom-observer/actions/runs/8242469524/job/22541465170#step:12:16):in `test_language_tracking'
```

**Comment by JoeCohen** [comment]
Closing because we need these files. Per emails from @pellaea:
> It looks like TranslationsController makes heavy use of the export files for building its forms.  I thought it only used the official export file.  Maybe there is a way to alter it to do that, but given how central a role they're playing right now, I have to revise my position on removing those files.

>[These files] really should be kept up to date as we add/remove/alter translations.  Basically, I wanted to make translators' job as easy as possible by grouping and ordering the translations helpfully.  Therefore it formats each language according to the official en.txt, complete with comments.  Then in the "translate this page" or "edit all translations" forms, it uses these export files to build the form for the translator, instead of just listing all of the strings bare in any old order without any comments or anything.  Again, in principle, it could do all this from the official en.txt and not use the unofficial export files.  But that seems to be way more work than required.  For just a few seconds saved each deploy! :)  And that's not even one of the longest steps of the deployment.
