### ISSUE TITLE
Supress "no such file" test console display

### ISSUE THREAD

**Issue by JoeCohen** [MushroomObserver/mushroom-observer#2025]
Fix this annoyance
```ruby
=======================grep: /home/runner/work/mushroom-observer/mushroom-observer/log/test.log: No such file or directory
/home/runner/work/mushroom-observer/mushroom-observer/script/extract_log:48:in `initialize': No such file or directory @ rb_sysopen - /home/runner/work/mushroom-observer/mushroom-observer/log/production.log (Errno::ENOENT)
```

**Comment by JoeCohen** [comment]
This somewhere in test/models
```ruby
joe@Josephs-iMac mushroom-observer % rails t test/models
Started with run options --seed 59953

ERROR QueuedEmailTest#test_verify_account_with_user (20.90s)
Minitest::UnexpectedError:         NoMethodError: undefined method `email' for nil
            app/mailers/verify_account_mailer.rb:10:in `build'
            app/models/queued_email/verify_account.rb:14:in `deliver_email'
            app/models/queued_email.rb:214:in `finish'
            app/models/queued_email/verify_account.rb:9:in `create_email'
            test/models/queued_email_test.rb:39:in `test_verify_account_with_user'

ERROR QueuedEmailTest#test_dump (20.93s)
Minitest::UnexpectedError:         NoMethodError: undefined method `dump' for nil
            test/models/queued_email_test.rb:16:in `test_dump'

grep: /Users/joe/mushroom-observer/log/test.log: No such file or directory=================================                             ] 77% Time: 00:00:24,  ETA: 00:00:07
  986/986: [===========================================================================================================================] 100% Time: 00:00:32, Time: 00:00:32

Finished in 32.71975s
986 tests, 15135 assertions, 0 failures, 2 errors, 0 skips
```

**Comment by JoeCohen** [comment]
It's in onde of the models starting with "s"
```ruby
% rails t test/models/s*
...
grep: /Users/joe/mushroom-observer/log/test.log: No such file or directory 
...
44 tests, 251 assertions, 0 failures, 0 errors, 0 skips
```

**Comment by JoeCohen** [comment]
It's here:
```ruby
% rails t test/models/script_test.rb -n /parse_log/                
grep: /Users/joe/mushroom-observer/log/test.log
```
In particular `status = system(cmd)`
```ruby
  test "parse_log" do
    script = script_file("parse_log")
    tempfile = Tempfile.new("test").path
    cmd = "#{script} 2>&1 > #{tempfile}"
    status = system(cmd)
    errors = File.read(tempfile)
    assert status, "Something went wrong with #{script}:\n#{errors}"
  end
```
