### ISSUE TITLE
test/models error

### ISSUE THREAD

**Issue by JoeCohen** [MushroomObserver/mushroom-observer#2040]
QueuedEmailTest throws errors when run on its own
The same thing happens with `rails t test/models`
```ruby
% rails t test/models/queued_email_test.rb
Started with run options --seed 15131

ERROR QueuedEmailTest#test_verify_account_with_user (1.13s)
Minitest::UnexpectedError:         NoMethodError: undefined method `email' for nil
            app/mailers/verify_account_mailer.rb:10:in `build'
            app/models/queued_email/verify_account.rb:14:in `deliver_email'
            app/models/queued_email.rb:214:in `finish'
            app/models/queued_email/verify_account.rb:9:in `create_email'
            test/models/queued_email_test.rb:39:in `test_verify_account_with_user'

ERROR QueuedEmailTest#test_dump (1.51s)
Minitest::UnexpectedError:         NoMethodError: undefined method `dump' for nil
            test/models/queued_email_test.rb:16:in `test_dump'
```

**Comment by JoeCohen** [comment]
This behaves differently when called on its own (`rails t test/models/queued_email_test.rb` versus during `rails t`
After `email.send_email`
- `QueuedEmail.count == 0` when called on its own
- `QueuedEmail.count == 1` during `rails t`
```ruby
  def test_dump
    subject = "Supercalifragilistic"
    note = "Phantasmagorical observations"
    email = QueuedEmail::UserQuestion.create_email(rolf, mary, subject, note)
    email.send_email
    dump = QueuedEmail.last.dump
    assert_match(/supercalifragilistic/i, dump)
    assert_match(/phantasmagorical/i, dump)
    assert_match(/rolf/i, dump)
    assert_match(/mary/i, dump)
  end
```
