### ISSUE TITLE
Show Project nonexistent ID Error

### ISSUE THREAD

**Issue by JoeCohen** [MushroomObserver/mushroom-observer#2519]
Cron Daemon <root@mushroomobserver.org> Sat, Nov 9, 2024 at 8:56 AM
To: webmaster@mushroomobserver.org
INFO -- : Started GET "/projects/141943" for 204.195.31.134 at 2024-11-09 16:55:10 +0000
INFO -- : Processing by ProjectsController#show as HTML
INFO -- : Parameters: {"id"=>"141943"}
WARN -- : user=4468 robot=N ip=204.195.31.134
INFO -- : Redirected to https://mushroomobserver.org/projects
INFO -- : Completed 500 Internal Server Error in 175ms (ActiveRecord: 158.0ms | Allocations: 3860)
E, [2024-11-09T16:55:10.865986 #3297821] ERROR -- :
NoMethodError (undefined method `id' for nil):
app/controllers/projects_controller.rb:156:in `set_ivars_for_show'
app/controllers/projects_controller.rb:24:in `show'
app/controllers/application_controller.rb:227:in `catch_errors_and_log_request_stats'

**Comment by JoeCohen** [comment]
Closing this. I cannot replicate it; pretty sure it was fixed.
